# Data Science Lifecycle

7 Steps

1. Business understanding
2. Data preparation
3. Data munging/Data wrangling
   - feature selection
   - EDA tool
4. Model training
5. model evaluation
6. Model deployment
   - AWS
   - IBM waston studio
7. Model tracking

# Data Science Libraries

- numpy
- pandas
- matplotlib
- seaborn

## numpy
- stands for numerical python
- developed in 2005 by Travis Oliphant
- we create arrays
   - 0-D
   - 1-D
   - 2-D
   - multi dimension
- linear algebra,fourier transforms,matrices
 

In [4]:
import numpy

In [5]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [6]:
import numpy as np

In [7]:
np.__version__

'1.20.1'

### CREATING ARRAYS

In [8]:
import numpy as np
x=np.array(23)
print(x)

23


In [9]:
# check dimension
np.ndim(x)

0

In [10]:
x1=np.array([12,23,4,5,6])
print(x1)
print(np.ndim(x1))

[12 23  4  5  6]
1


In [11]:
# 2D array
x2=np.array([[1,2,3]])
print(x2)
print(np.ndim(x2))

[[1 2 3]]
2


In [12]:
# 2D array
x2=np.array([[1,2,3],[1,3,4]])
print(x2)
print("dimension of x2:",np.ndim(x2))

[[1 2 3]
 [1 3 4]]
dimension of x2: 2


In [13]:
#to get the number of elements in x2 array
np.size(x2)

6

In [14]:
# to get no.of rows and columns
np.shape(x2)

(2, 3)

### 3D array
- [[[]]]

In [15]:
import numpy as np
x3=np.array([[[1,2,3],[4,5,6],[7,9,0]]])
print(x3)
print("dimension of x3:",np.ndim(x3))
print("elements of x3:",np.size(x3))
print("shape of x3:",np.shape(x3))

[[[1 2 3]
  [4 5 6]
  [7 9 0]]]
dimension of x3: 3
elements of x3: 9
shape of x3: (1, 3, 3)


### methods to create arrays
- zeros
- ones
- linspace
- logspace
- arrange
- random.rand

In [16]:
a0=np.zeros(3)
a0

array([0., 0., 0.])

In [17]:
a0=np.zeros(3,dtype=int)
a0

array([0, 0, 0])

In [18]:
a0=np.zeros(3,dtype=str)
a0

array(['', '', ''], dtype='<U1')

In [30]:
a1=np.ones(2,dtype=int)
a1

array([1, 1])

In [35]:
a1=np.ones(5,dtype=int)
print("a1:",a1)
a2=a1.reshape(5,1)
print("reshape of a1 into a2:\n",a2)
a3=a1.reshape(1,5)
print("reshape of a1 into a3:\n",a3)

a1: [1 1 1 1 1]
reshape of a1 into a2:
 [[1]
 [1]
 [1]
 [1]
 [1]]
reshape of a1 into a3:
 [[1 1 1 1 1]]


In [46]:
a=np.arange(1,22,4)
print(a)
print("dimension:",np.ndim(a))
print("elements:",np.size(a))

[ 1  5  9 13 17 21]
dimension: 1
elements: 6


## Possibilities to reshape of 6 elements
- (2,3)
- (3,2)
- (6,1)
- (1,6)

In [47]:
a1=a.reshape(3,2)
print(a)
print(a1)

[ 1  5  9 13 17 21]
[[ 1  5]
 [ 9 13]
 [17 21]]


In [57]:
l1=np.logspace(1,5,1)
print(l1)

[10.]


In [58]:
l2=np.linspace(1,5)
print(l2)

[1.         1.08163265 1.16326531 1.24489796 1.32653061 1.40816327
 1.48979592 1.57142857 1.65306122 1.73469388 1.81632653 1.89795918
 1.97959184 2.06122449 2.14285714 2.2244898  2.30612245 2.3877551
 2.46938776 2.55102041 2.63265306 2.71428571 2.79591837 2.87755102
 2.95918367 3.04081633 3.12244898 3.20408163 3.28571429 3.36734694
 3.44897959 3.53061224 3.6122449  3.69387755 3.7755102  3.85714286
 3.93877551 4.02040816 4.10204082 4.18367347 4.26530612 4.34693878
 4.42857143 4.51020408 4.59183673 4.67346939 4.75510204 4.83673469
 4.91836735 5.        ]


In [59]:
l2=np.linspace(1,5,6)
print(l2)

[1.  1.8 2.6 3.4 4.2 5. ]


In [60]:
r=np.random.rand(3,2)
print(r)

[[0.64872168 0.59874157]
 [0.46842808 0.66114334]
 [0.40969674 0.45304619]]


In [62]:
r1=np.random.randint(1,100)
print(r1)

28


In [63]:
r2=np.random.randn(1,10)
print(r2)

[[-0.49900968 -0.27940428  2.5026355   1.02908941 -0.46989755  0.28400488
  -0.74157339 -0.91266465 -0.22056617 -0.34627917]]


In [64]:
np.ndim(r2)

2

In [65]:
r3=r2.flatten()
print(r3)

[-0.49900968 -0.27940428  2.5026355   1.02908941 -0.46989755  0.28400488
 -0.74157339 -0.91266465 -0.22056617 -0.34627917]


In [66]:
np.ndim(r3)

1